host = '127.0.0.1'
port = 5866
dbname = 'highgo'
user='gitlab-runner'
password=''
#installation='/mnt/study/pg/installation'
installation='/home/gitlab-runner/HighGo/'
testcases='/home/gitlab-runner/regression/'
runner_output_to_streen=True
