host = '127.0.0.1'
port = 5866
dbname = 'highgo'
user='sunhuihui'
password=''
installation='/home/sunhuihui/hgdb5/'
testcases='/home/sunhuihui/regression/'
runner_output_to_streen=True
#runner_output_to_streen=False
