host = '127.0.0.1'
port = 5866
dbname = 'highgo'
user='sunhuihui'
password=''
installation='/home/sunhuihui/hgdb5/'
testcases='/home/sunhuihui/regression/'
html_report='/home/sunhuihui/regression/report_summary.html'
runner_output_to_streen=True
